name: Node.js CI/CD with Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        # On ne définit pas de mot de passe ici pour simplifier les tests en CI

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm install
        npm install --save-dev supertest

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Create .env file for tests
      run: |
        cat <<EOF > .env
        MONGO_URL=mongodb://localhost:27017/car_rental_test
        JWT_SECRET=${{ secrets.JWT_SECRET }}
        JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}
        JWT_EXPIRES_IN=15m
        JWT_REFRESH_EXPIRES_IN=7d
        baseURL=http://localhost:3000
        NODE_ENV=test
        EOF

    - name: Wait for MongoDB
      run: |
        until nc -z localhost 27017; do
          echo "Waiting for MongoDB..."
          sleep 1
        done

    - name: Run tests Jest
      env:
        MONGO_URL: mongodb://localhost:27017/car_rental_test
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
        NODE_ENV: test
      run: npm test

    - name: Run tests playwright
      run: npx playwright test 

    - name: Build Docker Image
      run: docker compose build

    # Le déploiement reste commenté
    # - name: Deploy
    #   if: github.ref == 'refs/heads/main'
    #   env:
    #     deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
    #   run: |
    #     curl "$deploy_url"